# .github/workflows/pipeline.yml
name: Nairaland Pipeline

on:
  schedule:
    - cron: "0 */6 * * *" # Run every 6 hours
  workflow_dispatch: # Allow  manual triggers

jobs:
  scrape-and-process:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run pipeline
        env:
          MONGO_URI: ${{ "mongodb+srv://Data-Engineerin-Proj:@Henry2802@cluster0.gl7po.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0" }}
        run: python main.py
